### ISSUE TITLE
PDO\PostViewRepository could show an outdated title and/or content

### ISSUE THREAD

**Issue by imefisto** [dddinphp/blog-cqrs#1]
Hi ! 

This is a very useful project in order to demonstrate CQRS/ES concepts. Thank you.

I've noted that the PDO/PostViewRepository could show an outdated title and/or content for a post with comments after a GET post/show/{id} request.

When the events PostContentWasChanged and PostTitleWasChanged are raised, the projections are made over "posts", leaving the fields "post_with_comments.title" and "post_with_comments.content" outdated.

You could update all the comments for a post with the new title and/or content (or just update that fields only for the first comment). Then it will be shown with the right title/content in the "show" request.

**Comment by theUniC** [comment]
If you still think this is something relevant feel free to send a PR. Thanks!
